// CSE 
// IT 
// BCA
// LAw 
// MAthematics
// Physics 
// Architecture
// Civil
export const facultyData = [
  {
    id: 1,
    name: " Dr. Anand Rajavat",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21027&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "A-101",
    email: "directorsviit@svvv.edu.in",
    phone: "+91 ----------",
    expertise: [
      "Computer Architecture",
      "Software Engineering",
      "System Management",
    ],
  },
  {
    id: 2,
    name: "Dr. Abhishek Singh Rathore",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=381&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "A-101",
    email: "abhishekatujjain@live.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 1000,
    name: "Prof. Atish Mishra",
    Designation: "Assistance Professior",
    labName: "",
    profileURL:
      "https://media.licdn.com/dms/image/v2/C4D03AQHglTVZJpn1cw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517492044706?e=1743033600&v=beta&t=TdUS6pTotLicwe3mkAj5SrojxLiYsYY5w81xeRvinHc",
    department: "Computer Science & Engineering",
    cabin: "A-101",
    email: "atishmishra@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Software Engineering", "Java", "DSA"],
  },
  {
    id: 3,
    name: "Dr. Rupali Bhartiya",
    Designation: "",
    labName: "",
    profileURL:
      "https://media.licdn.com/dms/image/v2/C4E03AQHY_SyhSXBbMw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517760964766?e=1743033600&v=beta&t=WJTThUqomHp2xMyTuQLHCQsWlbE9G0f4RWjdzHXIwfk",
    department: "Computer Science & Engineering",
    cabin: "Main block - SVVV/SVIIT/CSE/PG Block C /16",
    email: " rupalibhartiya@svvv.edu.in",
    phone: "+91 ----------",
    expertise: [
      "Network Security",
      "Distributed Systems",
      "Cyber Ethics and Social Media Analytics",
    ],
  },
  {
    id: 4,
    name: "Dr. Abhishek Sharma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221657&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "New LAB - SVVV/SVIIT/CSE/BLOCK 1/LAB /3",
    email: "abhisheksharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["TOC", "Operating System", "Compiler Design"],
  },
  {
    id: 5,
    name: "Ms. Shweta Pandey",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=10493&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "Main block - SVVV/SVIIT/CSE/BLOCK 1/C 10",
    email: "shweta.pandey2781@gmail.com",
    phone: "+91 ----------",
    expertise: [".", "Java"],
  },
  {
    id: 6,
    name: "Ms. Pooja Deshpande",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=379&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "Main block - SVVV/SVIIT/CSE/BLOCK 1/C 11",
    email: " poojadeshpande@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 7,
    name: "Dr. Harsh Pratap Singh",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=282147&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "MPL LAB - SVVV/SVIIT/CSE/BLOCK 1/c 18",
    email: "harshpratapsingh@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 8,
    name: "Mrs. Pallavi Kala",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=396&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "PG Block (IT) - SVVV/SVIIT/IT/PG Block C /08",
    email: "pallavikala.14june@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },

  {
    id: 9,
    name: "Mr. Sunny Bagga",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221654&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "",
    email: "sunny.bagga@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 10,
    name: "Mr. Sachin Sharma",
    Designation: "",
    labName: "",
    profileURL: " https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "sachinsharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Data Structure", "Opersting System"],
  },
  {
    id: 11,
    name: "Mr. Neeraj Mehta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221656&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: " neeraj.mehta@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 12,
    name: "Mr. Virendra Dani",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221655&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "virendra.dani@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 13,
    name: "Mr. Ankit Upadhyay",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221659&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "ankit.upadhyay@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 14,
    name: "Mr. SHYAM GEHLOT",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20616&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "shyamgehlot641@gmail.com",
    phone: "+91 ----------",
    expertise: ["Computer Network"],
  },
  {
    id: 15,
    name: "Mr. Pritesh Kumar Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://media.licdn.com/dms/image/v2/D4D03AQFDSGxykCT94g/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1642840643297?e=1743033600&v=beta&t=gj5eDByPgklZqvTOElj5jnCAopu-Qwioa5a1u_PdY2M",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "priteshkjain@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 16,
    name: "Mr. Akash Kanugo",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21208&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: " akashkanugo@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 17,
    name: "Mr. VIJAY KUMAR CHAUHAN",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=439&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: " vijay_38697@yahoo.co.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 18,
    name: "Mrs. KUSUM TILKAR",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=430&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "kusumtilkar@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 19,
    name: "Ms. Bharti Ahuja",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "bhartiahuja@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 20,
    name: "Ms. Gangeshwari Sharma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=282036&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "gangeshwarisharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 21,
    name: "Mr. VISHWAS DIXIT",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281846&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "vishwasdixit@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 22,
    name: "Mr. Nikhil Chaturvedi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=367&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "nikhilchaturvedi@svvv.edu.in",
    phone: "9589522331",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 23,
    name: "Mr. ALPESH SONI",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20777&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "alpeshsoni@svvv.edu.in",
    phone: "9993305588",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 24,
    name: "Mrs. NEHA AGRAWAL",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20777&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "neha.agrawal@svvv.edu.in",
    phone: "",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 25,
    name: "Mrs. Paridhi Nigam",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21031&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Science & Engineering",
    cabin: "C-303",
    email: "paridhinigam@svvv.edu.in",
    phone: "",
    expertise: ["Operating System", "Data Science"],
  },

  // IT faculties
  {
    id: 35,
    name: "Dr. Jigyasu Dubey",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21076&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "headit@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 36,
    name: "Mr. Sumit Kumar Nigam",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21045&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "nigam.sumit@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 37,
    name: "Mrs. Priyanka Gupta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21041&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "priyanka.guptacs@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 38,
    name: "Dr. Gaurav Shrivastava",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=339&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "gauravshrivastava@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 39,
    name: "Mrs. Priya Kothari",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Information Technology",
    cabin: "C-303",
    email: "priyakothari@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 40,
    name: "Mrs. RICHA JAIN",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=358&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "it.richajain@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 41,
    name: "Mr. Deepak Agrawal",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Information Technology",
    cabin: "C-303",
    email: "deepakagrawal@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 42,
    name: "Mr.Rahul Choudhary",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20562&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "rahul8svvv@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 43,
    name: "Mr. HARSHIT BHARTI",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=282260&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: " harshitbharti@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 44,
    name: "Mr. DEVENDRA KURIL",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281859&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "devendrakuril@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 45,
    name: "Mrs. Jagrati Nagdiya",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281732&resize=1&command=profile_pic&w=100&h=100",
    department: "Information Technology",
    cabin: "C-303",
    email: "jagratinagdiya@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },

  //BCA faculties
  {
    id: 50,
    name: "Dr. Saurabh Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=21181&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "saurabhjain@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 51,
    name: "Dr. Reena Gupta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=20909&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "reenagupta@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 52,
    name: "Dr. Raksha Chouhan",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=20967&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "rakshachouhan@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 53,
    name: "Dr Tanmay Kasbe",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=281718&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "tanmaykasbe@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 54,
    name: "Shri Sudarshan Dubey",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=10481&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "sudarshan.dubey@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 55,
    name: "Ms Priyanka Khanna",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=21086&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "priyankakhanna@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 56,
    name: "Prof Sonal John",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=21087&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "sonaljohn@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 57,
    name: "Prof Bhawesh Joshi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=21305&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "bhaweshjoshi@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 58,
    name: "Mrs Aachal Sharma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282160&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "aanchalsharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 59,
    name: "Ms Shilpa Jaiswal",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Computer Applications",
    cabin: "C-303",
    email: "shilpajaiswal@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 60,
    name: "Mrs. Swati Sharma",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Computer Applications",
    cabin: "C-303",
    email: "swatisharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 61,
    name: "Ms Priyasi Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=281848&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "priyasijain@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 62,
    name: "Prof. Shruti Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=281849&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "shrutijain@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 63,
    name: "Ms Visheshta Kushwah",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282244&resize=1&command=profile_pic&w=100&h=100",
    department: "Computer Applications",
    cabin: "C-303",
    email: "visheshtakushwah@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 64,
    name: "",
    Designation: "",
    labName: "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282245&resize=1&command=profile_pic&w=100&h=100",
    profileURL: "Mr. Mridul Tiwari",
    department: "Computer Applications",
    cabin: "C-303",
    email: " mridultewari@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 65,
    name: "Mrs. Priyanka Sharma",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Computer Applications",
    cabin: "C-303",
    email: " priyankasharma@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },

  //law

  {
    id: 81,
    name: "Dr. Ashutosh Bairagi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282203&resize=1&command=profile_pic&w=100&h=100",
    department: "Law",
    cabin: "C-303",
    email: "ashutosh393@gmail.com",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 82,
    name: "Ms. Mansi Trivedi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=20921&resize=1&command=profile_pic&w=100&h=100",
    department: "Law",
    cabin: "C-303",
    email: "mansi.trivedi@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 83,
    name: "Mr. Pranay R Patel",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Law",
    cabin: "C-303",
    email: "pranaypatel@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 84,
    name: "Ms. Shreya Singh Parihar",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282240&resize=1&command=profile_pic&w=100&h=100",
    department: "Law",
    cabin: "C-303",
    email: "Shreyaparihar@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 85,
    name: "Mr. Shantanu Sudheer Shastri",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Law",
    cabin: "C-303",
    email: "shantanushastri@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 86,
    name: "Mrs Jagruti Gupta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/UserPanel/ImageViewer.aspx?imgID=282279&resize=1&command=profile_pic&w=100&h=100",
    department: "Law",
    cabin: "C-303",
    email: " jagrutigupta@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 87,
    name: "Ms. Priya Nigam",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Law",
    cabin: "C-303",
    email: " priyanigam@svvv.edu.in",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },
  {
    id: 88,
    name: "Ms. Doorav",
    Designation: "",
    labName: "",
    profileURL: "https://svvv.edu.in/images/system/noprofile.jpg",
    department: "Law",
    cabin: "C-303",
    email: "",
    phone: "+91 ----------",
    expertise: ["Operating System", "Data Science"],
  },

  // Mathemaics Department
  {
    id: 105,
    name: "Dr. Shobha Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20874&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "shobajain1@yahoo.com",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 106,
    name: "Ms. PRIYA ASALMOL",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20846&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "priyaasalmol@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 107,
    name: "Dr. Nayna",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20870&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "naynakadam@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 108,
    name: "Dr. Satish Shukla",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20793&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "satishmathematics@yahoo.co.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 109,
    name: "Dr. SWATI CHOURSIYA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20831&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "swati.choursiya09@gmail.com",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 110,
    name: "Dr. shilpa rahurikar",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20833&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "shilparahurikar@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 111,
    name: "Dr. NIKITA DUBEY",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20840&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "nikitadubey@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 112,
    name: "Dr. Seema Bagora",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20839&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "bagoraseema@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 113,
    name: "Mrs. Varsha Pathak",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=31427&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: "varshapathak@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  {
    id: 114,
    name: "Dr. Praveen Kumar Sharma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=41435&resize=1&command=profile_pic&w=100&h=100",
    department: "Mathematics",
    cabin: "C-303",
    email: " praveensharma@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Discerte Structure"],
  },
  
  // Physics Department

  {
    id: 140,
    name: "Dr. Suprajnya Thakur",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20851&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "suprajnyathakur@svvv.edu.in",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 141,
    name: "Dr. Ravi Vanshpal",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20913&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "ravivanshpal@gmail.com",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 142,
    name: "Dr. AARTEE SHARMA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21115&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "aartee.sharma08@gmail.com",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 143,
    name: "Dr. NITU KATARIYA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21116&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "nitukatariya@svvv.edu.in",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 144,
    name: "Dr. PRAGYA PALOD",
    Designation: "",
    labName: "",
    profileURL:
      "",
    department: "Physics Department",
    cabin: "C-303",
    email: "pragyapalod@svvv.edu.in",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 145,
    name: "Dr. UTTAM SHARMA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21113&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "druttamsharma1971@gmail.com",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 146,
    name: "Dr. Neeraj Sahu",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281838&resize=1&command=profile_pic&w=100&h=100",
    department: "Physics Department",
    cabin: "C-303",
    email: "neerajsahu@svvv.edu.in",
    phone: "+91 *******",
    expertise: [""],
  },
  
  

  // Architecture
  {
    id: 200,
    name: "Mr. Vishal Yardi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=111479&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "saurabhjain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 201,
    name: "Mrs. Navajyothi Mahenderkar Subhedar",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21315&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "navajyothisubhedar@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 202,
    name: "Mr. Abhijit Kulkarni",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=345&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "abhijit.aj2@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 203,
    name: "Ms. Samiksha Bhatt",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20918&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "samikshadesign@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 204,
    name: "Ms. RUCHIKA SHARMA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=221671&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-30",
    email: "ruchika.sharma@svvv.edu.in",
    phone: "+91 *******",
    expertise: [""],
  },
  {
    id: 205,
    name: "Mrs. VINAMRATA SUGANDHI",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=271703&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "vinamratasugandhi@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 206,
    name: "Mrs. Sonal Singh Purohit",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281709&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "sonalsingh@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Environmental Planning"],
  },
  {
    id: 207,
    name: "Mr. Rahul Gangrade",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=282034&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "rahulgangrade@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 208,
    name: "Mrs. POORVEE KHARGONKAR",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281706&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "purvikhargonkar@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 209,
    name: "Mrs. Priyanka Agrawal",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=281706&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-303",
    email: "priyankaagrawal@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 210,
    name: "Mrs. Ruchika Gangrade",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=261685&resize=1&command=profile_pic&w=100&h=100",
    department: "Architecture",
    cabin: "C-30",
    email: "ruchika.gangrade@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 211,
    name: "Ms. Shubha Suryavanshi",
    Designation: "",
    labName: "",
    profileURL: "",
    department: "Architecture",
    cabin: "C-303",
    email: "shubhasuryavanshi@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },

  //civil engineering

  {
    id: 251,
    name: "Dr. Ananda Babu K",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20593&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "bujjianand@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 252,
    name: "Prof. Sudhanshu Dube",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21151&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "sudhanshudube28@rediffmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 253,
    name: "Mrs. Rekha Shinde",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=416&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "rekhashinde23@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 254,
    name: " Mr. Rohan Borade",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=417&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: " rohanborade08@rediffmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 255,
    name: "Mrs. Rupali Goud",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=418&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "rupali.goud05@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 256,
    name: "Mr. Rakesh Verma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=420&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "rakeshverma3388@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 257,
    name: "Mrs. Shilpa Indra Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21132&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "shilpajain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },

  {
    id: 258,
    name: "Mr. Vaibhav Singh",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=419&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "vaibhavsingh@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 259,
    name: "Mr. Gaurav Awasthi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=421&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "gaurava91@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 260,
    name: "Dr. Chinar Garg",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20564&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "chinaragrawal@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 261,
    name: "Ms. Oshin Victor",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20561&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "oshinvictor@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 262,
    name: "Mr. Abhishek Jhanjhot",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21197&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "abhishek.jhanjhot@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 263,
    name: "Mr. VIJAYANT PANDAY",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20899&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "vijayantcivil@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 264,
    name: "Mr. Rahul Sharma",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=423&resize=1&command=profile_pic&w=100&h=100",
    department: "Civil Engineering",
    cabin: "C-303",
    email: "sharmarahulce@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },

  //EE department
  {
    id: 301,
    name: "Dr. Namit Gupta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21122&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "director_svits@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Embedded Systems", "Microprocessors and Microcontrollers"],
  },
  {
    id: 302,
    name: "Mr. Anil Kumar Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=455&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "svits.electrical@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 303,
    name: "Mr. Preet Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21131&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "preetjain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 304,
    name: "Mrs. Anjali Gupta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21150&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "chitraanjali@yahoo.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 305,
    name: "Mrs. Shraddha Mohanty",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21243&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "shraddhamohanty@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 306,
    name: "Ms. Toshi Mandloi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=436&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "toshi_oshin@yahoo.co.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 307,
    name: "Mrs. Ankita Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21124&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "ankitajain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 308,
    name: "Mrs. Neha Maheshwari",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20812&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "nehamaheshwari@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 309,
    name: "Ms. Alka Karketta",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21166&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "alkakarketta@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 310,
    name: "Mr. Jitendra Managre",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=411&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "jitendramanagre@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 311,
    name: "Mr. Nilesh Patidar",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21138&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "nileshpatidar@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 312,
    name: "Dr. Shiraz Husain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=10516&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "shirazhusain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 313,
    name: "Mr. Dilip Mandloi",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21144&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "dilipmandloi@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 314,
    name: "Mr. NARESH PUROHIT",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=20728&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "nareshpurohit@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id:315,
    name: "Mr. DEEPAK RATHOD",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21156&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "deepakrthd9@gmail.com",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 316,
    name: "Mr. Shrikant Dandotiya",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21203&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "shrikantdandotiya@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 317,
    name: "Mr. LALIT BHANWRELA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21158&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "lalitbhanwrela@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 318,
    name: "Dr. Swapnil Jain",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21249&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "swapniljain@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },
  {
    id: 319,
    name: "Mr. ROHAN GUPTA",
    Designation: "",
    labName: "",
    profileURL:
      "https://svvv.edu.in/userpanel/ImageViewer.aspx?imgID=21123&resize=1&command=profile_pic&w=100&h=100",
    department: "Electrical and Electronics Engineering",
    cabin: "C-303",
    email: "rohangupta@svvv.edu.in",
    phone: "+91 *******",
    expertise: ["Energy Efficiency in buildings"],
  },

];
