export const SyllabusData = [
    // 2022
    {
        department:"B.Tech",
        batch:"2022-26",
        branch:"information Technology",
        sem:"1",
        syllabusLink:"dv",
    },
    {
        department:"B.Tech",
        batch:"2022-26",
        branch:"information Technology",
        sem:"2",
        syllabusLink:"dv",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"Computer Science",
        sem:"1",
        syllabusLink:"dv",
    },
    {
        department:"Bachlers of Technology",
        batch:"2023-27",
        branch:"Computer Science",
        sem:"2",
        syllabusLink:"dv",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"Computer Science",
        sem:"3",
        syllabusLink:"dv",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"Computer Science",
        sem:"4",
        syllabusLink:"dv",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"IT",
        sem:"1",
        syllabusLink:"dvzdfgdfi",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"IT",
        sem:"2",
        syllabusLink:"2nd sem",
    },
    {
        department:"B.Tech",
        batch:"2023-27",
        branch:"IT",
        sem:"3",
        syllabusLink:"dv",
    },
]