export const SyllabusData = [
  // 2022-26 /& 2021-25
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "1",
    syllabusName: "I_Master_Syllabus_CSE-BTech(CSE)-2021-22",
    syllabusLink:
      "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/I_Master_Syllabus_CSE-BTech(CSE)-2021-22.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "2",
    syllabusName: "II_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/II_Syllabus-SVIIT-CSE-BTech(CSE)-2021-22-(Credit-24)-%7BWoS%7D.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "3",
    syllabusName: "III_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/Syllabus_CSE_III_Sem_21-22.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "4",
    syllabusName: "IV_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/Syllabus_CSE_IV_Sem_21_22.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "5",
    syllabusName: "V_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/btech_cse_5th_syllabus_21_25_20.07.2023.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "6",
    syllabusName: "VI_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/btech_cse_6th_syllabus_21_25_20.07.2023.pdf",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "CSE, CC, CYFS, BDA",
    sem: "7",
    syllabusName: "VII_Master_Syllabus_CSE-BTech(CSE)-2021-2",
    syllabusLink: "https://svvv.edu.in/department/SyllabusComputer%20Science%20&%20Engineering/SVIIT_Syllabus_BT_CSE_VII-SEM__21-25_01.08.2024.pdf.",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "Information and Technology",
    sem: "2",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech / B.tech+MBA / M.tech",
    batch: "2022-26",
    branch: "Information and Technology",
    sem: "1",
    syllabusName: "dv",
    syllabusLink: "dv",
  },

  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "1",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "2",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "3",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "4",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "5",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "6",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "IBM - DS/FSDB/BDA/CMC/AI",
    sem: "7",
    syllabusName: "dv",
    syllabusLink: "dv",
  },

  {
    department: "B.Tech",
    batch: "2022-26",
    branch: "AI & ML",
    sem: "1",
    syllabusName: "dv",
    syllabusLink: "dv",
  },

  {
    department: "Bachlers of Technology",
    batch: "2023-27",
    branch: "Computer Science",
    sem: "2",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2023-27",
    branch: "Computer Science",
    sem: "3",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2023-27",
    branch: "Computer Science",
    sem: "4",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
  {
    department: "B.Tech",
    batch: "2023-27",
    branch: "IT",
    sem: "1",
    syllabusName: "dv",
    syllabusLink: "dvzdfgdfi",
  },
  {
    department: "B.Tech",
    batch: "2023-27",
    branch: "IT",
    sem: "2",
    syllabusName: "Syllabus 2323- 27 B.Tech/MBS/M.tech CSE ",
    syllabusLink: "https://mui.com/material-ui/getting-started/installation/",
  },
  {
    department: "B.Tech",
    batch: "2023-27",
    branch: "IT",
    sem: "3",
    syllabusName: "dv",
    syllabusLink: "dv",
  },
];
