export const TeamData = [
  {
    id: 14,
    name: "Jatin Rane",
    profileimg:"https://media.licdn.com/dms/image/v2/D4D03AQH-em9d1eUC_Q/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1729446947821?e=1743033600&v=beta&t=rVoOJO6UuxmF0lJyvxKNHYMHZiaMqjbkFAmMS7Odfkc",
    description: "Hi, I am Jatin Rane, the Team Leader responsible for developing and designing the website, and also guiding our team towards achieving goals with collaboration and efficiency.",
    linkedin: "https://www.linkedin.com/in/jatinrane/",
    Github: "https://github.com/jatinrane14/",
    instagram: "https://www.instagram.com/jatinrane_14/",
  },
  {
    id: 12,
    name: "Sneha Jain", 
    profileimg:"https://media.licdn.com/dms/image/v2/D4D03AQHR6mkkXqoRQQ/profile-displayphoto-shrink_400_400/B4DZSOV51IGkAo-/0/1737554896009?e=1743033600&v=beta&t=perlQIZkjMxVsk-ZXpNj8Dbi5B7NsVMciVVh5nUhJik",
    description: "Hi, I am Sneha Jain, the Design Lead responsible for creating and refining the website’s visual and user experience, and also guiding our team to ensure creativity and consistency in design.",
    linkedin: "https://www.linkedin.com/in/sneha-jain-697452292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    Github: "https://github.com/sneha2085",
    instagram: "https://www.instagram.com/_.sneha__jain/",
  },
  {
    id: 2,
    name: "Kratika Gupta",
    profileimg:"https://media.licdn.com/dms/image/v2/D4E03AQFX_iftKpGpJA/profile-displayphoto-shrink_400_400/B4EZSEuyS4HAAs-/0/1737393646042?e=1743033600&v=beta&t=yfVISP0BmevLiVyKM1ZG43usNViwamxlOrKZZPKHMWo",
    description: "Hi, I am Kratika Gupta, responsible for collecting and organizing faculty details and also help to design the user interface, and also ensuring accuracy and completeness in the gathered information.",
    linkedin: "https://www.linkedin.com/in/kratika-gupta-848225347/",
    Github: "https://github.com/KratikaGupta02",
    instagram: "https://www.instagram.com/kratikaaaa2006/",
  },
  {
    id: 1,
    name: "Aaryesh Namdeo",
    profileimg:"https://media.licdn.com/dms/image/v2/D5603AQH2d3wFa3TExg/profile-displayphoto-shrink_400_400/B56ZSOSwxZHsAg-/0/1737554071971?e=1743033600&v=beta&t=34T5UvEPmpbEJmECkJkOw9vJsZ7PWfOL_o3cFT4acL8",
    description: "Hi, I am Aaryesh Namdeo, the responsible for designning the user interfacce, collecting faculty details and also Testing the functionality of the Site.",
    linkedin: "https://www.linkedin.com/in/aaryeah-namdeo-29294a1b4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    Github: "",
    instagram: "https://www.instagram.com/iamaaryesh_n/",
  },
];